#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/crontabs

# create symlinks
symlinks=(usr/share/webapps/betisier/include/config.inc.php)

for i in "${symlinks[@]}"; do
	[[ -e "$i" && ! -L "$i" ]] && mv "$i" "${i}.bak"
	[[ ! -L "$i" ]] && ln -s "/config/$(basename "$i")" "$i"
done

# backwards compatibility
if grep -q 'root /config/www/betisier/' /config/nginx/site-confs/default; then
	cp /defaults/default /config/nginx/site-confs/default
fi

# permissions
chown -R abc:abc \
	/usr/share/webapps/betisier \
	/config
